<?php
function redirect_relationship_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'redirect_relationship') . '/includes/views',
    'template path' => drupal_get_path('module', 'redirect_relationship') . '/themes',
  );
}

function redirect_relationship_form_redirect_edit_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][1] = $form['#submit'][0];
  $form['#submit'][0] = 'redirect_relationship_edit_form_submit';
}

function redirect_relationship_edit_form_submit(&$form, &$form_state) {
  if(preg_match('~(?P<nodetext>node/)(?P<nid>\d+)~',$form_state['values']['redirect'],$matches)) {
    $form_state['values']['nid'] = $matches['nid'];
  }
}